# Suma matrices

$$
c_{ij} = a_{ij} + b{ij}
$$

In [3]:
import numpy as np;

e = np.array([[8,2,1],
              [-5,6,7]]);
f = np.array([[3,4,0],
              [4,-3,9]]);
g = np.zeros([2,3]);


for i in range(len(e)):
    for j in range(len(e[0])):
        g[i][j] = e[i][j] + f[i][j];
print(g);

[[11.  6.  1.]
 [-1.  3. 16.]]



2
3


# Ponderacion por escalar

$$
b_{ij} = k \cdot a_{ij}
$$

multiplicar una matriz por un escalar k

In [6]:
import numpy as np;

M = np.array([[20,16,18], 
              [12,34,32], 
              [56,22,6], 
              [24,14,28], 
              [18,8,30]]);
k = 2.5;
P = np.zeros([len(M), len(M[0])]);

for i in range(len(M)):
    for j in range(len(M[0])):
        P[i][j] = k * M[i][j];
print(P)

[[ 50.  40.  45.]
 [ 30.  85.  80.]
 [140.  55.  15.]
 [ 60.  35.  70.]
 [ 45.  20.  75.]]


# Matriz transpuesta
$$
b_{ij} = a_{ji}, i = 1, 2, ..., n; j = 1, 2, ..., m
$$

In [1]:
import numpy as np;

A = np.array([[3,8], 
              [5,1], 
              [2,6]]);
At = np.zeros([len(A[0]),len(A)]);

print(At)

for i in range(len(At)):
    for j in range(len(At[0])):
        At[i][j] = A[j][i];
print("\n\n");
print(At)

[[0. 0. 0.]
 [0. 0. 0.]]



[[3. 5. 2.]
 [8. 1. 6.]]
